version: '3.8'

networks:
  podman:
    driver: bridge

services:
  infinispan:
    image: quay.io/infinispan/server
    container_name: infinispan
    restart: unless-stopped
    networks:
      - podman
    ports:
      - "11222:11222"
    environment:
      USER: "admin"
      PASS: "admin"
    volumes:
      - infinispan_data:/opt/infinispan/server/data
      - infinispan_log:/opt/infinispan/server/log
      - infinispan_config:/opt/infinispan/server/config

  ldap:
    image: osixia/openldap:latest
    container_name: apacheds
    restart: unless-stopped
    networks:
      - podman
    ports:
      - "1389:389"   # Porta LDAP
      - "1636:636"   # Porta LDAPS (se abilitata)
    environment:
      LDAP_ORGANISATION: "Example Corp"
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "supersecurepassword"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  postgres:
    image: postgres:15
    container_name: keycloak-db
    restart: unless-stopped
    networks:
      - podman
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - keycloak_db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    depends_on:
      - postgres
      - ldap
    networks:
      - podman
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db  # Usa il nome del container
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: supersecurepassword
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: supersecurepassword
      KC_HEALTH_ENABLED: "true"
    command: ["start-dev"]

volumes:
  ldap_data:
  ldap_config:
  keycloak_db:
  infinispan_data:
  infinispan_log:
  infinispan_config:

